language: node_js
node_js:
  - "6"
  - "4"
  - "0.12"
  - "0.10"
  - "0.8"
install:
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  - "npm install -g npm"
  - "npm install -g grunt-cli"
  - "npm install"
  - "./node_modules/.bin/node-gyp install"
matrix:
  fast_finish: true
