language: node_js
node_js:
  - "10"
  - "8"
  - "6"
env:
  - NODE_GYP_VERSION=3
  - NODE_GYP_VERSION=2
  - NODE_GYP_VERSION=1
install:
  - "npm install"
  - "npm install node-gyp@$NODE_GYP_VERSION"
  - "npx node-gyp install"
