language: node_js
node_js:
  - "10"
  - "8"
  - "6"
env:
  global:
    - CXX=g++-4.8
  matrix:
    - NODE_GYP_VERSION=3
    - NODE_GYP_VERSION=2
    - NODE_GYP_VERSION=1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - "npm install -g grunt-cli"
  - "npm install"
  - "npm install node-gyp@$NODE_GYP_VERSION"
  - "./node_modules/.bin/node-gyp install"
matrix:
  fast_finish: true
