language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "0.8"
  - iojs-v1
install:
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  - "npm install -g npm"
  - "npm install -g grunt-cli"
  - "npm install"
  - "./node_modules/.bin/node-gyp install"
matrix:
  allow_failures:
    - node_js: iojs-v1
  fast_finish: true
