build: off
shallow_clone: true
version: "{build}"

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "4"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g grunt-cli
  - npm install
  - .\node_modules\.bin\node-gyp install

test_script:
  - node --version
  - npm --version
  - cmd: grunt test
