build: off
shallow_clone: true
version: "{build}"

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "4"
    - nodejs_version: "0.8"
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  # Otherwise it won’t use the updated npm version
  - SET PATH=%APPDATA%\npm;%PATH%
  - npm install -g npm
  - npm install -g grunt-cli
  - npm install
  - .\node_modules\.bin\node-gyp install

test_script:
  - node --version
  - npm --version
  - cmd: grunt test
