environment:
  matrix:
    - nodejs_version: "14"
    - nodejs_version: "12"
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npx node-gyp install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
